services:
  - type: web
    name: laravel-portfolio
    env: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Laravel Portfolio"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:xBjDMNEY8X2kfIIKrvpsHyLIabhyHsSDde2oyzUDDpo=
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://laravel-portfolio-2mkg.onrender.com
      - key: FORCE_HTTPS
        value: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d178jhgdl3ps73a5o7d0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: laravel_portfolio_db_3k2n
      - key: DB_USERNAME
        value: laravel_portfolio_db_3k2n_user
      - key: DB_PASSWORD
        value: HgjNNxdG1JqVqIBo8PwIQsudR3IBJTNK
