services:
  - type: web
    name: laravel-portfolio
    env: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_HOST
        value: dpg-d178jhgdl3ps73a5o7d0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: laravel_portfolio_db_3k2n
      - key: DB_USERNAME
        value: laravel_portfolio_db_3k2n_user
      - key: DB_PASSWORD
        value: HgjNNxdG1JqVqIBo8PwIQsudR3IBJTNK
    startCommand: |
      php artisan migrate --seed && apache2-foreground
