services:
  - type: web
    name: laravel-portfolio
    env: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Laravel Portfolio"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:xBjDMNEY8X2kfIIKrvpsHyLIabhyHsSDde2oyzUDDpo=
      - key: APP_DEBUG
        value: true
    startCommand: |
      echo "=== STARTING BASIC TEST ===" &&
      echo "Checking Apache config..." &&
      apache2ctl -t &&
      echo "Testing PHP..." &&
      php -v &&
      echo "Checking document root..." &&
      ls -la /var/www/html/public/ &&
      echo "Testing basic PHP file..." &&
      php -r "echo 'PHP is working';" &&
      echo "Starting Apache..." &&
      apache2-foreground
